package config

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sync"

	"github.com/luaxlou/glow/pkg/api"
	"github.com/spf13/viper"
)

const (
	EnvConfig    = "OP_APP_CONFIG"
	EnvServerURL = "OP_SERVER_URL"
	EnvAppName   = "OP_APP_NAME"
)

var (
	v    *viper.Viper
	once sync.Once

	AppIdentity string
)

func checkVerbose() bool {
	for _, arg := range os.Args {
		if arg == "-v" || arg == "--verbose" {
			return true
		}
	}
	return false
}

func verboseLog(format string, v ...any) {
	if checkVerbose() {
		log.Printf("[VERBOSE] "+format, v...)
	}
}

func getLocalConfigFile() string {
	appName := os.Getenv(EnvAppName)
	if appName == "" {
		appName = AppIdentity
	}
	if appName != "" {
		return fmt.Sprintf("%s_local_config.json", appName)
	}
	return "local_config.json"
}

func load() {
	once.Do(func() {
		v = viper.New()
		v.SetConfigType("json")

		localConfigFile := getLocalConfigFile()
		// Try loading from local config file
		if _, err := os.Stat(localConfigFile); err == nil {
			f, err := os.Open(localConfigFile)
			if err == nil {
				defer f.Close()
				if err := v.MergeConfig(f); err != nil {
					log.Printf("Warning: Failed to parse local config file: %v", err)
				} else {
					log.Printf("Loaded config from %s", localConfigFile)
					if checkVerbose() {
						allSettings := v.AllSettings()
						jsonSettings, _ := json.MarshalIndent(allSettings, "", "  ")
						verboseLog("Initial Local Config Data: \n%s", string(jsonSettings))
					}
				}
			}
		}
	})
}

// Start is deprecated and no longer connects to AppCenter.
// Apps now only read local config files generated by `glow apply`.
// This function is kept for backward compatibility but does nothing.
func Start(appInfo api.AppInfo) {
	load()
	// No longer connects to AppCenter/TCP
	verboseLog("Config loaded from local file (AppCenter connection disabled)")
}

// ProvisionResource is deprecated and no longer functional.
// Resource provisioning should now be done via `glow apply -f app.yaml`.
// This function returns an error indicating the new approach.
func ProvisionResource(resourceType, resourceName string) (map[string]any, error) {
	return nil, fmt.Errorf("ProvisionResource is deprecated. Use 'glow apply -f app.yaml' with spec.resources.%s declared instead", resourceType)
}

// Register is deprecated. Use Start instead (which now only loads local config).
func Register(appInfo api.AppInfo) error {
	Start(appInfo)
	return nil
}

// Get unmarshals a specific key into the target structure.
// This works for both the JSON blob and individual environment variables.
func Get(key string, target interface{}) error {
	load()
	sub := v.Sub(key)
	if sub != nil {
		return sub.Unmarshal(target)
	}

	// If it's a simple value (not a nested object), Unmarshal the main viper
	return v.UnmarshalKey(key, target)
}

// IsSet checks if a configuration key exists.
func IsSet(key string) bool {
	load()
	return v.IsSet(key)
}
